export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const FETCH_TRIPS = 'FETCH_TRIPS';
export const SEARCH_COUNTRY = 'SEARCH_COUNTRY';
export const FETCH_SEARCH_COUNTRIES = 'FETCH_SEARCH_COUNTRIES';